name: "Download All Target Comparison Artifacts"
description: "Downloads all the artifacts for all targets needed for run comparison"
inputs:
  applied_glibchash:
    required: true
  baseline_glibchash:
    required: true
  token:
    required: true
  repo:
    required: true

runs:
  using: "composite"
  steps:
    # Download applied

    - name: Download rv64gc
      uses: ./.github/actions/common/download-comparison-artifacts
      with:
        report-artifact-name: applied-rv64gc-lp64d-${{ inputs.applied_glibchash }}-testsuite-filter-report.log
        binary-artifact-name: applied-rv64gc-lp64d-${{ inputs.applied_glibchash }}-rootfs-test
        github-token: ${{ inputs.token }}
        repo: ${{ inputs.repo }}

    - name: Download rv64gcv
      uses: ./.github/actions/common/download-comparison-artifacts
      with:
        report-artifact-name: applied-rv64gcv-lp64d-${{ inputs.applied_glibchash }}-testsuite-filter-report.log
        binary-artifact-name: applied-rv64gcv-lp64d-${{ inputs.applied_glibchash }}-rootfs-test
        github-token: ${{ inputs.token }}
        repo: ${{ inputs.repo }}

    # Download baseline

    - name: Download rv64gc
      uses: ./.github/actions/common/download-comparison-artifacts
      with:
        report-artifact-name: baseline-rv64gc-lp64d-${{ inputs.baseline_glibchash }}-testsuite-filter-report.log
        binary-artifact-name: baseline-rv64gc-lp64d-${{ inputs.baseline_glibchash }}-rootfs-test
        github-token: ${{ inputs.token }}
        repo: ${{ inputs.repo }}

    - name: Download rv64gcv
      uses: ./.github/actions/common/download-comparison-artifacts
      with:
        report-artifact-name: baseline-rv64gcv-lp64d-${{ inputs.baseline_glibchash }}-testsuite-filter-report.log
        binary-artifact-name: baseline-rv64gcv-lp64d-${{ inputs.baseline_glibchash }}-rootfs-test
        github-token: ${{ inputs.token }}
        repo: ${{ inputs.repo }}

    # End download
