name: "Run testsuite"
description: "Runs testsuite"
inputs:
  target:
    description: 'target arch-abi'
    required: true
  glibchash:
    description: 'glibchash'
    required: true

runs:
  using: "composite"
  steps:
      - name: Run testsuite
        shell: bash
        working-directory: riscv-gnu-toolchain/build
        run: |
          GLIBC_BIN_PATH=$(pwd)/bin
          echo $GLIBC_BIN_PATH
          ls $GLIBC_BIN_PATH
          cd build-glibc-linux-${{ inputs.target }}
          PATH=$GLIBC_BIN_PATH:$PATH make check -j $(nproc) -k || true

      - name: Build sum files zip
        shell: bash
        working-directory: riscv-gnu-toolchain
        run: |
          mkdir sum_files
          mkdir out_files
          mkdir test_result_files
          for file in `find build/build-glibc-linux-${{ inputs.target }} -name "*.sum"`; do cp -r --parents $file sum_files; done
          zip -r glibc-linux-${{ inputs.target }}-${{ inputs.glibchash }}-sum-files.zip sum_files

          for file in `find build/build-glibc-linux-${{ inputs.target }} -name "*.out"`; do cp -r --parents $file sum_files; done
          zip -r glibc-linux-${{ inputs.target }}-${{ inputs.glibchash }}-out-files.zip sum_files

          for file in `find build/build-glibc-linux-${{ inputs.target }} -name "*.test-result"`; do cp -r --parents $file sum_files; done
          zip -r glibc-linux-${{ inputs.target }}-${{ inputs.glibchash }}-test-result-files.zip sum_files

      - name: Upload sum file artifacts
        uses: actions/upload-artifact@v3
        with:
          name: glibc-linux-${{ inputs.target }}-${{ inputs.glibchash }}-sum-files
          path: |
            riscv-gnu-toolchain/glibc-linux-${{ inputs.target }}-${{ inputs.glibchash }}-sum-files.zip
          retention-days: 90

      - name: Upload out file artifacts
        uses: actions/upload-artifact@v3
        with:
          name: glibc-linux-${{ inputs.target }}-${{ inputs.glibchash }}-out-files
          path: |
            riscv-gnu-toolchain/glibc-linux-${{ inputs.target }}-${{ inputs.glibchash }}-out-files.zip
          retention-days: 90

      - name: Upload test-result file artifacts
        uses: actions/upload-artifact@v3
        with:
          name: glibc-linux-${{ inputs.target }}-${{ inputs.glibchash }}-test-result-files
          path: |
            riscv-gnu-toolchain/glibc-linux-${{ inputs.target }}-${{ inputs.glibchash }}-test-result-files.zip
          retention-days: 90
