FROM riscv64/ubuntu:22.04

RUN apt-get update 
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
  autoconf \
  automake \
  autotools-dev \
  curl \
  python3 \
  python3-pip \
  libmpc-dev \
  libmpfr-dev \
  libgmp-dev \
  gawk \
  build-essential \
  bison \
  flex \
  texinfo \
  gperf \
  libtool \
  patchutils \
  bc \
  zlib1g-dev \
  libexpat-dev \
  ninja-build \
  git \
  cmake \
  libglib2.0-dev \
  openssh-server 


#RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin without-password/' /etc/ssh/sshd_config

#RUN useradd -m -s /bin/bash root-1
#RUN echo "root:pass" | chpasswd
#RUN echo "root-1:pass" | chpasswd

#RUN mkdir /home/root-1/.ssh
#RUN mkdir /root/.ssh

#EXPOSE 22

#ENTRYPOINT service ssh start && bash

