name: "Setup Env"
description: "Sets up the environment"
inputs:
  free_up_space:
    description: 'Do (or dont) free up space by deleting unused libraries. Defaults to false'
    required: false
    default: 'false'
  python_libs:
    description: 'Do (or do not) download python libraries. Defaults to false'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
      - name: Initialize glibc
        shell: bash
        working-directory: ./
        run: |
          git submodule update --init glibc

      - name: Remove unneeded frameworks to recover disk space
        shell: bash
        if: inputs.free_up_space == 'true'
        run: |
          echo "-- Before --"
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android

          sudo rm -rf /opt/microsoft
          sudo rm -rf /opt/google
          sudo rm -rf /opt/az  # Azure
          sudo rm -rf /opt/actionarchivecache
          sudo rm -rf /opt/mssql-tools
          
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf /opt/hostedtoolcache/Ruby
          sudo rm -rf /opt/hostedtoolcache/go
          sudo rm -rf /opt/hostedtoolcache/node

          # sudo rm -rf /usr/lib/jvm

          sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/share/az*
          sudo rm -rf /usr/share/rubygems-integration
          sudo rm -rf /usr/share/zsh
          sudo rm -rf /usr/share/monodoc
          sudo rm -rf /usr/share/emacs*
          sudo rm -rf /usr/share/postgresql*

          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/local/share/aws*

          # Postcommit remove dashboards
          rm -rf dashboard
          
          echo "-- After --"
          df -h

      - name: Download qemu
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y qemu-system-misc qemu-user-static


      - name: Download python libraries
        shell: bash
        if: inputs.python_libs == 'true'
        run: |
          sudo apt update
          sudo apt install -y libmariadb-dev libmariadb3 qemu-system-misc qemu-user-static
          sudo apt remove python3-pip
          wget https://bootstrap.pypa.io/get-pip.py
          sudo python3 get-pip.py
          pip install -U pyopenssl cryptography mariadb==1.0.11 gnupg pygit2 requests

       
