name: "Setup Env"
description: "Sets up the environment"
inputs:
  free_up_space:
    description: 'Do (or dont) free up space by deleting unused libraries. Defaults to false'
    required: false
    default: 'false'
  python_libs:
    description: 'Do (or do not) download python libraries. Defaults to false'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
      - name: Initialize riscv-gnu-toolchain
        shell: bash
        working-directory: ./
        run: |
          git submodule update --init riscv-gnu-toolchain
          git submodule update --init glibc-cicd

      - name: Remove unneeded frameworks to recover disk space
        shell: bash
        if: inputs.free_up_space == 'true'
        run: |
          echo "-- Before --"
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          echo "-- After --"
          df -h

      - name: Download python libraries
        shell: bash
        if: inputs.python_libs == 'true'
        run: |
          sudo apt update
          sudo apt install -y libmariadb-dev libmariadb3
          sudo apt remove python3-pip
          wget https://bootstrap.pypa.io/get-pip.py
          sudo python3 get-pip.py
          pip install -U pyopenssl cryptography mariadb==1.0.11 gnupg pygit2 requests

       
